<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "knockout": {
                            "component": "Orange_HelloWorld/js/knockout",
                            "template" : "Orange_HelloWorld/knockout",
                            "dataUrl": "<?php echo $block->getUrl('helloworld/index/save'); ?>"
                        }
                    }
                }
            }
        }
</script>
<div data-bind="scope: 'knockout'">
<!-- ko template: getTemplate() --><!-- /ko -->
</div>
